# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict   # checks for files that contain merge conflict strings.

  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: bun x markdownlint-cli --fix
        language: system
        files: \.md$
        pass_filenames: true
